var a = 10;
document.write("Result:<br>The value of a is: " + a);
document.write("<br>--------------------------------------<br>");
document.write("<br>The value of ++a is: " + ++a);
document.write("<br>Now the value of a is: " + a + "<br>");
document.write("<br>The value of a++ is: " + a++);
document.write("<br>Now the value of a is: " + a + "<br>");
document.write("<br>The value of --a is: " + --a);
document.write("<br>Now the value of a is: " + a + "<br>");
document.write("<br>The value of a-- is: " + a--);
document.write("<br>Now the value of a is: " + a + "<br>");
